{{- if .Values.backend.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "patchmon.fullname" . }}-agent-files
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patchmon.labels" . | nindent 4 }}
  {{- with .Values.backend.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.backend.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size | quote }}
  {{- $storageClass := include "patchmon.storageClass" (dict "local" .Values.backend.persistence.storageClass "global" .Values.global) }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass }}
  {{- end }}
{{- end }}
