{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "patchmon.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patchmon.database.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.database.service.type }}
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.database.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "patchmon.database.selectorLabels" . | nindent 4 }}
{{- end }}
