{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "patchmon.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patchmon.redis.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "patchmon.fullname" . }}-redis
  replicas: {{ .Values.redis.replicaCount }}
  {{- if .Values.redis.updateStrategy }}
  updateStrategy:
    {{- toYaml .Values.redis.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "patchmon.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "patchmon.redis.selectorLabels" . | nindent 8 }}
      {{- with .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ include "patchmon.redis.image" . }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command:
            - redis-server
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "patchmon.redis.secretName" . }}
                  key: {{ .Values.redis.auth.existingSecretPasswordKey }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
              protocol: TCP
          {{- if .Values.redis.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - "--no-auth-warning"
                - "-a"
                - "$(REDIS_PASSWORD)"
                - ping
            initialDelaySeconds: {{ .Values.redis.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.redis.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.redis.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - redis-cli
                - "--no-auth-warning"
                - "-a"
                - "$(REDIS_PASSWORD)"
                - ping
            initialDelaySeconds: {{ .Values.redis.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.redis.readinessProbe.failureThreshold }}
          {{- end }}
          {{- with .Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.redis.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: redis-data
        {{- with .Values.redis.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- range .Values.redis.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size | quote }}
        {{- $storageClass := include "patchmon.storageClass" (dict "local" .Values.redis.persistence.storageClass "global" .Values.global) }}
        {{- if $storageClass }}
        storageClassName: {{ $storageClass }}
        {{- end }}
  {{- end }}
{{- end }}
