{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "patchmon.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patchmon.redis.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.redis.service.type }}
  clusterIP: None
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "patchmon.redis.selectorLabels" . | nindent 4 }}
{{- end }}
