{{- if .Values.secret.create -}}
{{- $secretName := printf "%s-secrets" (include "patchmon.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patchmon.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  # Always use top-level values for secret creation
  {{- if not .Values.database.auth.existingSecret }}
    {{- if not .Values.database.auth.password }}
      {{- fail "You must set database.auth.password or database.auth.existingSecret" }}
    {{- end }}
    postgres-password: {{ .Values.database.auth.password | b64enc | quote }}
  {{- end }}
  {{- if not .Values.redis.auth.existingSecret }}
    {{- if not .Values.redis.auth.password }}
      {{- fail "You must set redis.auth.password or redis.auth.existingSecret" }}
    {{- end }}
    redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- end }}
  {{- if not .Values.backend.existingSecret }}
    {{- if not .Values.backend.jwtSecret }}
      {{- fail "You must set backend.jwtSecret or backend.existingSecret" }}
    {{- end }}
    jwt-secret: {{ .Values.backend.jwtSecret | b64enc | quote }}
    {{- if not .Values.backend.aiEncryptionKey }}
      {{- fail "You must set backend.aiEncryptionKey or backend.existingSecret" }}
    {{- end }}
    ai-encryption-key: {{ .Values.backend.aiEncryptionKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.backend.oidc.enabled (not .Values.backend.oidc.existingSecret) }}
    {{- if not .Values.backend.oidc.clientSecret }}
      {{- fail "You must set backend.oidc.clientSecret or backend.oidc.existingSecret" }}
    {{- end }}
    oidc-client-secret: {{ .Values.backend.oidc.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
